export function getRuleProto(rule: any): any;
export var multiMatchs: string[];
export var protocols: string[];
export var pureResProtocols: string[];
export var reqProtocols: string[];
export var resProtocols: string[];
export var aliasProtocols: {
    ruleFile: string;
    ruleScript: string;
    rulesScript: string;
    reqScript: string;
    reqRules: string;
    resRules: string;
    pathReplace: string;
    download: string;
    skip: string;
    'http-proxy': string;
    'xhttp-proxy': string;
    status: string;
    hosts: string;
    xhost: string;
    html: string;
    js: string;
    reqMerge: string;
    css: string;
    excludeFilter: string;
    includeFilter: string;
    P: string;
};
export function getRules(): any;
export function isBinProtocol(protocol: any): 1 | 3 | 2 | undefined;
export function resetRules(rules: any): any;
export function isResRule(protocol: any): boolean;
export function isWebProtocol(protocol: any): boolean;
export function isWebsocketProtocol(protocol: any): boolean;
export function isFileProxy(protocol: any): boolean;
export function contains(name: any): boolean;
